// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bash_test

import (
	"litdoc/internal"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutputParser creates a new instance of MockOutputParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputParser {
	mock := &MockOutputParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutputParser is an autogenerated mock type for the OutputParser type
type MockOutputParser struct {
	mock.Mock
}

type MockOutputParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputParser) EXPECT() *MockOutputParser_Expecter {
	return &MockOutputParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockOutputParser
func (_mock *MockOutputParser) Parse(litdoc internal.Block, following []internal.Block) (internal.Output, int, error) {
	ret := _mock.Called(litdoc, following)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 internal.Output
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(internal.Block, []internal.Block) (internal.Output, int, error)); ok {
		return returnFunc(litdoc, following)
	}
	if returnFunc, ok := ret.Get(0).(func(internal.Block, []internal.Block) internal.Output); ok {
		r0 = returnFunc(litdoc, following)
	} else {
		r0 = ret.Get(0).(internal.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(internal.Block, []internal.Block) int); ok {
		r1 = returnFunc(litdoc, following)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(internal.Block, []internal.Block) error); ok {
		r2 = returnFunc(litdoc, following)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOutputParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockOutputParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - litdoc internal.Block
//   - following []internal.Block
func (_e *MockOutputParser_Expecter) Parse(litdoc interface{}, following interface{}) *MockOutputParser_Parse_Call {
	return &MockOutputParser_Parse_Call{Call: _e.mock.On("Parse", litdoc, following)}
}

func (_c *MockOutputParser_Parse_Call) Run(run func(litdoc internal.Block, following []internal.Block)) *MockOutputParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Block
		if args[0] != nil {
			arg0 = args[0].(internal.Block)
		}
		var arg1 []internal.Block
		if args[1] != nil {
			arg1 = args[1].([]internal.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputParser_Parse_Call) Return(output internal.Output, n int, err error) *MockOutputParser_Parse_Call {
	_c.Call.Return(output, n, err)
	return _c
}

func (_c *MockOutputParser_Parse_Call) RunAndReturn(run func(litdoc internal.Block, following []internal.Block) (internal.Output, int, error)) *MockOutputParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
