// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bash_test

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(script string) (string, string, int, error) {
	ret := _mock.Called(script)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 string
	var r2 int
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, string, int, error)); ok {
		return returnFunc(script)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(script)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(script)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) int); ok {
		r2 = returnFunc(script)
	} else {
		r2 = ret.Get(2).(int)
	}
	if returnFunc, ok := ret.Get(3).(func(string) error); ok {
		r3 = returnFunc(script)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - script string
func (_e *MockRunner_Expecter) Run(script interface{}) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run", script)}
}

func (_c *MockRunner_Run_Call) Run(run func(script string)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(stdout string, stderr string, exitCode int, err error) *MockRunner_Run_Call {
	_c.Call.Return(stdout, stderr, exitCode, err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(script string) (string, string, int, error)) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
