// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package internal_test

import (
	"litdoc/internal"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCell creates a new instance of MockCell. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCell(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCell {
	mock := &MockCell{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCell is an autogenerated mock type for the Cell type
type MockCell struct {
	mock.Mock
}

type MockCell_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCell) EXPECT() *MockCell_Expecter {
	return &MockCell_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCell
func (_mock *MockCell) Execute() (internal.Cell, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 internal.Cell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (internal.Cell, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() internal.Cell); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.Cell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCell_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCell_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockCell_Expecter) Execute() *MockCell_Execute_Call {
	return &MockCell_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockCell_Execute_Call) Run(run func()) *MockCell_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCell_Execute_Call) Return(cell internal.Cell, err error) *MockCell_Execute_Call {
	_c.Call.Return(cell, err)
	return _c
}

func (_c *MockCell_Execute_Call) RunAndReturn(run func() (internal.Cell, error)) *MockCell_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function for the type MockCell
func (_mock *MockCell) Render() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCell_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockCell_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
func (_e *MockCell_Expecter) Render() *MockCell_Render_Call {
	return &MockCell_Render_Call{Call: _e.mock.On("Render")}
}

func (_c *MockCell_Render_Call) Run(run func()) *MockCell_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCell_Render_Call) Return(s string, err error) *MockCell_Render_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCell_Render_Call) RunAndReturn(run func() (string, error)) *MockCell_Render_Call {
	_c.Call.Return(run)
	return _c
}
