// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package internal_test

import (
	"litdoc/internal"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCellParser creates a new instance of MockCellParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCellParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCellParser {
	mock := &MockCellParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCellParser is an autogenerated mock type for the CellParser type
type MockCellParser struct {
	mock.Mock
}

type MockCellParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCellParser) EXPECT() *MockCellParser_Expecter {
	return &MockCellParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockCellParser
func (_mock *MockCellParser) Parse(block internal.Block, following []internal.Block) (internal.Cell, int, error) {
	ret := _mock.Called(block, following)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 internal.Cell
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(internal.Block, []internal.Block) (internal.Cell, int, error)); ok {
		return returnFunc(block, following)
	}
	if returnFunc, ok := ret.Get(0).(func(internal.Block, []internal.Block) internal.Cell); ok {
		r0 = returnFunc(block, following)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internal.Cell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(internal.Block, []internal.Block) int); ok {
		r1 = returnFunc(block, following)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(internal.Block, []internal.Block) error); ok {
		r2 = returnFunc(block, following)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCellParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockCellParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - block internal.Block
//   - following []internal.Block
func (_e *MockCellParser_Expecter) Parse(block interface{}, following interface{}) *MockCellParser_Parse_Call {
	return &MockCellParser_Parse_Call{Call: _e.mock.On("Parse", block, following)}
}

func (_c *MockCellParser_Parse_Call) Run(run func(block internal.Block, following []internal.Block)) *MockCellParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Block
		if args[0] != nil {
			arg0 = args[0].(internal.Block)
		}
		var arg1 []internal.Block
		if args[1] != nil {
			arg1 = args[1].([]internal.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCellParser_Parse_Call) Return(cell internal.Cell, n int, err error) *MockCellParser_Parse_Call {
	_c.Call.Return(cell, n, err)
	return _c
}

func (_c *MockCellParser_Parse_Call) RunAndReturn(run func(block internal.Block, following []internal.Block) (internal.Cell, int, error)) *MockCellParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
